### ISSUE TITLE
Generating a spoiler-free multiword creates worlds for the spoilers files as well

### ISSUE THREAD

**Issue by Foopyo** [ori-rando/ui#101]
![Ori_and_the_Will_of_the_Wisps_Randomizer_2022-02-22-17-58-12](https://user-images.githubusercontent.com/25066858/155180994-21ac75f7-e9e5-4678-90d8-da0c86cf3819.png)
When using the "Disable spoilers" option on a multiworld, the Game page will creates Worlds for the .spoilers files as well

**Comment by timoschwarzer** [comment]
Was a server issue, is fixed now.
