### ISSUE TITLE
Tracker settings category

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/ui#115]
Currently all tracker-related settings are listed under "Launch settings", namely:
- Builtin tracker always on top
- Builtin tracker transparent
- Ignore mouse in builtin tracker
- Show willow hearts in builtin tracker

These don't really have to do with the game launch, they might be better under a "Tracker" category.

"Launch with Item Tracker" would then be ambiguous about its category, I'd feel that the tracker category would be the stronger relationship to put it into.

**Comment by Mawex** [comment]
changed layout in 1.9.0
