### ISSUE TITLE
Locked games and/or spectator links

### ISSUE THREAD

**Issue by MunWolf** [ori-rando/ui#145]
Allow the creator of a game to lock it and prevent people from joining (and also unlock it)
Could also be implemented as a password but lock/unlock is probably easier.

Also include a spectator link where you get to see the bingo board (should not need to login etc when looking at that link).

This is the UI part of https://github.com/ori-rando/wotw-server/issues/68

**Comment by timoschwarzer** [comment]
Done in 2.0. Backported to 1.10.0.
