### ISSUE TITLE
Bingo setting: hide other teams score

### ISSUE THREAD

**Issue by Mawex** [ori-rando/ui#146]
new bingo setting:
hiding the score (collected cards and lines) of other teams

**Comment by timoschwarzer** [comment]
Proposal: Replace the score with - when clicking on it

**Comment by Mawex** [comment]
holding `ctrl` while clicking to hide it for all teams?

Note: teams with hidden score should not be sorted by their score. Or could be ordered with a score of zero.

**Comment by timoschwarzer** [comment]
Yea, they should be sorted down.

**Comment by timoschwarzer** [comment]
Implemented with https://github.com/ori-rando/ui/commit/719236362a76be9fe610f4ca69dcee890bbb7c10
