### ISSUE TITLE
Don't play the "progress animation" when the goal is completed

### ISSUE THREAD

**Issue by Foopyo** [ori-rando/ui#15]
The little flash which appears when you are getting progress on bingo goals don't need to be played when the player already have completed the goal.
The same is true if someone else already completed a goal in lockout bingo since you can't get that goal anymore afterwards.

**Comment by timoschwarzer** [comment]
> The same is true if someone else already completed a goal since you can't get that goal anymore afterwards.

That only applies to lockout bingo though.
