### ISSUE TITLE
Generator tab checkboxes

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/ui#42]
The "Hard Mode" and "Disable Spoilers" checkboxes in the generator tab get toggled even if you press on the far right end of the column.

This leads to me often toggling them accidentally (such as while clicking out of one of the input fields to the right)) and not even noticing it.

Instead the click event listener could be limited to the length of the text component, since that is the visual delimiter of what "belongs" to the checkbox.

**Comment by timoschwarzer** [comment]
Fixed in https://github.com/ori-rando/ui/commit/75e8748ffa187563e8bc27e236d797d358e991b9
