### ISSUE TITLE
Launching seeds takes multiple attempts

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/ui#63]
When launching the randomizer from a seed file, the first time running the seed only the launcher starts, the game does not and the current seed doesn't update.
When running the seed a second time in this state, it actually launches the game and updates the current seed.

**Comment by timoschwarzer** [comment]
Only in 1.1 beta or does this happen in 1.0 too?

**Comment by SiriusAshling** [comment]
This is on 1.0.9

**Comment by timoschwarzer** [comment]
Fixed in 1.1.0-beta.7
